package largebeb.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RegistrationResponseDTO {

    // Message explaining the result of the operation
    private String message;

    // Unique identifier generated by mongodb
    private String id;

    // The role assigned to the user
    private String role;
}